DROP DATABASE IF EXISTS shopdb;

CREATE DATABASE shopdb DEFAULT CHARACTER SET utf8;

USE shopdb;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS cart_entry;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;

CREATE TABLE cart
(
    code VARCHAR(45) NOT NULL,
    PRIMARY KEY (code)
);
CREATE TABLE category
(
    code INT(11)      NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (code)
);
CREATE TABLE product
(
    code          INT(11)      NOT NULL,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(255) NOT NULL,
    image         VARCHAR(255) NOT NULL,
    price         DOUBLE       NOT NULL,
    category_code INT(11)      NOT NULL,
    quantity      INT(11)      NOT NULL,
    PRIMARY KEY (code),
    CONSTRAINT fk_category_for_product FOREIGN KEY (category_code) REFERENCES category (code) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE cart_entry
(
    code         VARCHAR(45) NOT NULL,
    quantity     DOUBLE      NOT NULL,
    product_code INT(11)     NOT NULL,
    cart_code    VARCHAR(45) NOT NULL,
    PRIMARY KEY (code),
    CONSTRAINT fk_products_in_cart_product FOREIGN KEY (product_code) REFERENCES product (code) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_products_in_cart_cart1 FOREIGN KEY (cart_code) REFERENCES cart (code) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE user
(
    uid        BIGINT(19)  NOT NULL,
    first_name VARCHAR(45)  DEFAULT NULL,
    last_name  VARCHAR(45)  DEFAULT NULL,
    username   VARCHAR(45)  DEFAULT NULL,
    password   VARCHAR(255) DEFAULT NULL,
    salt       VARCHAR(45)  DEFAULT NULL,
    image      VARCHAR(255) DEFAULT NULL,
    cart_code  VARCHAR(45) NOT NULL,
    PRIMARY KEY (uid),
    CONSTRAINT fk_cart_for_user FOREIGN KEY (cart_code) REFERENCES cart (code) ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO `category`
VALUES ('1', 'Laptops'),
       ('2', 'Phones'),
       ('3', 'Speakers'),
       ('4', 'Monitors'),
       ('5', 'Headphones'),
       ('6', 'Printers');

INSERT INTO `product`
VALUES ('116679', 'et',
        'Nihil accusantium odit qui aliquid similique voluptates voluptas. Odit aut consequuntur et beatae. Impedit reprehenderit id omnis nam hic magni.',
        'product_placeholder.png', '690.42', '3', '473'),
       ('117265', 'neque',
        'Eligendi atque ipsam totam quis. Voluptatibus est repellendus ut minima dolores dolorum. Natus perferendis quos cumque maiores voluptas neque et. Quia possimus molestiae earum necessitatibus odio ea.',
        'product_placeholder.png', '1774.67', '4', '277'),
       ('139989', 'laudantium',
        'Modi rerum quia et placeat eligendi molestiae similique nostrum. Est delectus omnis magni et. Veritatis et unde id quo. Expedita quis velit accusamus necessitatibus dolores.',
        'product_placeholder.png', '1390.54', '6', '27'),
       ('153179', 'soluta',
        'Laboriosam animi neque et adipisci suscipit ea consequatur. Et error illo ipsam est consequatur ea. Esse deleniti quisquam harum quod dolore doloribus. Voluptas iure laudantium ut dolor non qui.',
        'product_placeholder.png', '1267.7', '5', '123'),
       ('179971', 'ea',
        'Quisquam ut laudantium iusto assumenda ea. Rem labore est suscipit velit qui non. Mollitia magni iusto natus explicabo sint.',
        'product_placeholder.png', '34.24', '6', '980'),
       ('182892', 'ut',
        'Nihil odit impedit praesentium voluptate architecto libero. Quos praesentium sit rerum qui sit ex facilis provident.',
        'product_placeholder.png', '493.89', '1', '534'),
       ('187566', 'et',
        'Dolores eum ipsum possimus non quisquam enim. Saepe velit ut molestiae ut aperiam blanditiis a adipisci. Minima laudantium qui dolorem itaque iusto velit illum. Et unde eum consequuntur nemo est exercitationem.',
        'product_placeholder.png', '1574.05', '3', '328'),
       ('188887', 'ab',
        'Minus quia exercitationem quia ipsa excepturi. Nam et voluptas necessitatibus voluptatem. Explicabo libero beatae non laborum. Et qui qui magni facere doloremque et dolorum.',
        'product_placeholder.png', '770.86', '6', '942'),
       ('191285', 'qui',
        'Est temporibus fugiat nihil sed mollitia magnam ullam enim. Est tenetur corrupti facere et. Doloremque aspernatur facere quo dolor exercitationem. Qui vitae et eos temporibus.',
        'product_placeholder.png', '1185.28', '4', '217'),
       ('191692', 'ea',
        'Necessitatibus sit magnam molestiae voluptatibus corporis placeat. Natus dicta amet velit in. Officia enim ea velit qui reprehenderit officia id.',
        'product_placeholder.png', '1352.52', '3', '22'),
       ('212324', 'in',
        'Rerum rem libero earum possimus. Labore nesciunt odio sit. Asperiores velit dolor qui provident. Sunt modi et occaecati eum distinctio. Impedit sed qui facere.',
        'product_placeholder.png', '1942.04', '2', '684'),
       ('223928', 'velit', 'Omnis quia aliquid omnis ea. Ut et aut est ut delectus doloribus. Neque eos vel repudiandae.',
        'product_placeholder.png', '967.94', '3', '737'),
       ('231478', 'eos',
        'Vel et quis est odit. Suscipit earum et delectus impedit tenetur. Sint doloremque similique iusto aut dolores ipsum. Dolore est nisi eveniet autem.',
        'product_placeholder.png', '226.54', '2', '544'),
       ('251643', 'unde', 'Ratione ea earum possimus voluptatibus. Qui ut perspiciatis occaecati necessitatibus.',
        'product_placeholder.png', '62.57', '5', '927'),
       ('251803', 'et',
        'Voluptatem velit sed atque ea aut ut ad veniam. Sit in minus totam soluta ut dicta perferendis. Aut ut nulla itaque fugiat qui est et.',
        'product_placeholder.png', '304.6', '2', '588'),
       ('264962', 'fugit',
        'Qui cupiditate nihil sunt et eos sit eius. Dolore at dolor reprehenderit non. Tenetur libero quis dolorem incidunt. Ratione voluptatem qui enim.',
        'product_placeholder.png', '837.65', '6', '406'),
       ('265712', 'ad',
        'Ullam est nihil ut deleniti illum. Provident illum exercitationem ut harum ad voluptatem. Sit voluptates aperiam hic est alias.',
        'product_placeholder.png', '999.47', '5', '796'),
       ('276535', 'error',
        'In iure veritatis sed quidem. Vitae nihil neque sunt vel. Porro ut quia ut ab ut doloribus. Sit quae asperiores fuga pariatur deleniti facere.',
        'product_placeholder.png', '312.29', '2', '590'),
       ('283493', 'quis', 'Id eos aliquid fuga ipsa molestias odit ab. Corrupti assumenda totam id placeat quos aspernatur assumenda.',
        'product_placeholder.png', '1301.99', '1', '571'),
       ('287877', 'pariatur',
        'Aut deserunt aspernatur et eos ut odio. Perspiciatis neque doloribus hic sint vel ratione iusto. Officia animi exercitationem assumenda quo.',
        'product_placeholder.png', '634.51', '3', '999'),
       ('301015', 'ab',
        'Doloremque et ut soluta. Maiores consectetur animi nihil nam reiciendis voluptatem sit. Porro placeat ex vel excepturi consequatur cupiditate. Aspernatur perferendis doloremque laborum ut.',
        'product_placeholder.png', '693.08', '4', '221'),
       ('314424', 'rerum',
        'Assumenda quasi nam eaque est vero quia. Ea architecto est modi omnis. Et enim cupiditate vel commodi omnis ut maiores.',
        'product_placeholder.png', '1533.03', '1', '868'),
       ('328626', 'sint', 'Quasi sed aliquid sunt sequi officia eius. Dolores sit accusantium nam exercitationem qui.',
        'product_placeholder.png', '965.25', '1', '356'),
       ('331483', 'deserunt',
        'Culpa corrupti in id nam quisquam cupiditate. Est nihil dolore explicabo alias. Quia odit cupiditate officia esse eum laudantium et. Laboriosam et amet omnis est qui eos.',
        'product_placeholder.png', '417.77', '4', '730'),
       ('337865', 'mollitia', 'Beatae id distinctio sint aliquam tempora. Et molestias qui facere minima quis.', 'product_placeholder.png',
        '1677.9', '1', '401'),
       ('353333', 'culpa',
        'Recusandae voluptatem dolorem possimus quis. Autem ut enim et magnam quaerat. Nemo quod quo consequatur sed. Fugiat cum autem est quia consequuntur optio.',
        'product_placeholder.png', '1579.72', '5', '941'),
       ('365085', 'numquam',
        'Ut et eum omnis rerum quidem nobis. Necessitatibus rerum vero doloribus ad sint. Qui aliquid architecto et excepturi voluptatem occaecati et.',
        'product_placeholder.png', '598.93', '3', '301'),
       ('385864', 'nobis', 'At ut et rerum aut eaque et. Suscipit aliquam velit numquam. Corporis non autem dolorem dolorum.',
        'product_placeholder.png', '807.64', '6', '860'),
       ('395890', 'porro',
        'Omnis velit et voluptatem asperiores voluptatem quis. Consequatur cupiditate optio harum maxime aliquid veniam. Similique ipsum quam autem quae. Reiciendis in itaque natus rerum voluptatem vitae.',
        'product_placeholder.png', '372.4', '1', '506'),
       ('413716', 'earum',
        'Rerum tempora eos impedit ad. Quis consequuntur iusto ratione provident voluptatem. Inventore totam a officia quo.',
        'product_placeholder.png', '384.86', '5', '759'),
       ('420019', 'expedita',
        'Et dignissimos tenetur enim mollitia facilis atque sapiente. Nobis dolor molestiae beatae velit autem tempore error voluptatum. Et culpa nihil et aut.',
        'product_placeholder.png', '1219.84', '4', '704'),
       ('428861', 'accusantium',
        'Iusto neque rerum eius qui quisquam. Natus atque sint nihil aut perspiciatis cupiditate ut. Autem eaque sed id laudantium delectus quo asperiores accusantium. Ratione dignissimos rerum distinctio iusto quis repellat est omnis. Explicabo enim qui excepturi',
        'product_placeholder.png', '69.63', '5', '196'),
       ('429643', 'quisquam',
        'Consequatur molestiae officiis est architecto. Saepe est ut distinctio voluptas similique. Nesciunt autem velit quae reiciendis natus porro fuga.',
        'product_placeholder.png', '1493.67', '2', '628'),
       ('436921', 'pariatur',
        'Quidem temporibus ratione inventore non et. Ipsa hic commodi nobis veniam. Alias voluptas dolorem omnis vero et. Quis porro aut explicabo non.',
        'product_placeholder.png', '1760.88', '6', '222'),
       ('447869', 'rerum',
        'Eius corporis est ut consectetur totam nam molestiae. Fugiat eos vel tempora id commodi dolore nisi. Dignissimos facilis repellendus omnis voluptas provident.',
        'product_placeholder.png', '102.34', '3', '926'),
       ('459183', 'id', 'Magnam minima asperiores aut. Harum atque et non minus laborum et. Soluta ullam enim fugit enim veniam.',
        'product_placeholder.png', '510', '6', '19'),
       ('477655', 'qui', 'Vero consequatur amet ut vitae deleniti non. Ipsa sit et iure et. Maiores assumenda qui officiis soluta et sit.',
        'product_placeholder.png', '1206.75', '3', '14'),
       ('490853', 'animi',
        'Assumenda voluptatum ut quis illo vel animi quas. Vel porro quis exercitationem est. Vero ea voluptatem fugit quia. Accusantium aut maiores quia soluta.',
        'product_placeholder.png', '242.24', '4', '33'),
       ('493079', 'veritatis', 'Soluta et eius deleniti et modi. Voluptates voluptas est fugit id.', 'product_placeholder.png', '735.71',
        '6', '153'),
       ('493808', 'cumque',
        'Officiis sint et et sint doloremque. Possimus cumque in enim recusandae non numquam iusto. Nemo asperiores omnis omnis deleniti corporis fugiat officiis.',
        'product_placeholder.png', '553.23', '2', '915'),
       ('504864', 'velit',
        'Debitis dolores consectetur hic modi quam. Deserunt minus sed esse et qui. Aliquid eaque ut dolorem similique. Aspernatur nisi minus ut quasi atque aliquam sed qui.',
        'product_placeholder.png', '867.3', '3', '31'),
       ('508469', 'reprehenderit',
        'Alias quasi aut cupiditate placeat alias qui facilis. Qui sit neque et est quaerat et omnis architecto. Excepturi placeat temporibus totam dolores error labore dicta rerum. Nihil nostrum qui culpa quia dolores quidem rerum.',
        'product_placeholder.png', '1268.55', '1', '217'),
       ('511681', 'praesentium',
        'Repellat autem et voluptatem consequatur corrupti in. Et aut vero porro nisi odio quis voluptatum. Rem rem totam corporis vitae ipsam consectetur dolore corrupti. Praesentium rem ut repudiandae excepturi. Rerum rerum veniam ut.',
        'product_placeholder.png', '1062.83', '3', '213'),
       ('511932', 'ex',
        'Qui laboriosam incidunt sit optio suscipit harum. Quasi aut reiciendis cum ea. Ipsa omnis ipsum beatae doloremque ut. Velit aut consequatur earum atque sunt tenetur.',
        'product_placeholder.png', '1252.55', '2', '367'),
       ('523886', 'ipsum',
        'Nihil et maxime quia amet enim rerum. Dolorem non ab porro. Animi dolor ut molestias veniam voluptates soluta. Nemo saepe sint et ut harum. Doloribus id voluptate sit distinctio est unde praesentium.',
        'product_placeholder.png', '200.91', '3', '754'),
       ('524601', 'repellat',
        'In blanditiis doloremque possimus. Molestias dolorem sit eaque porro fuga amet voluptas. Facilis ducimus blanditiis necessitatibus sed aliquid. Odit perferendis eum molestias et qui.',
        'product_placeholder.png', '880.17', '4', '90'),
       ('531712', 'repellat',
        'Et voluptatem molestiae labore hic. Ut repellendus sint iusto dicta sit hic dolores. Aperiam occaecati laudantium suscipit natus. Minus assumenda est asperiores rerum.',
        'product_placeholder.png', '811.73', '4', '537'),
       ('540098', 'magnam',
        'Et debitis ad aliquam sint blanditiis. Excepturi est magnam doloremque non dignissimos consequatur. Explicabo perspiciatis quia sed. Aut magni nihil iusto natus expedita ut.',
        'product_placeholder.png', '1596.89', '1', '165'),
       ('561358', 'aut',
        'Dolorem aut incidunt autem aut. Illum enim quis nisi tempora fuga. Id aut nostrum quaerat nihil. Non eaque voluptatem quia eos consequatur.',
        'product_placeholder.png', '938.2', '6', '404'),
       ('562007', 'architecto',
        'Iure laboriosam vel minus tempora sed quam. Deleniti est atque iusto voluptatem. Consectetur et eligendi ipsa porro commodi consequatur quaerat eaque.',
        'product_placeholder.png', '1646.73', '2', '421'),
       ('571727', 'autem',
        'Quia in et qui corrupti molestiae. Mollitia veritatis molestiae eos. Sit quae sint vel tenetur et repellat asperiores. Inventore eum quas quasi velit necessitatibus incidunt.',
        'product_placeholder.png', '403.43', '6', '851'),
       ('580727', 'quo',
        'Repellendus reiciendis corporis cupiditate aut sunt. Eveniet vero rerum nobis minus in iste. Rerum odio delectus cumque et atque qui. Veritatis eos id cupiditate nihil cupiditate dolor. Occaecati tempora qui iusto optio.',
        'product_placeholder.png', '1639.63', '2', '244'),
       ('583054', 'quasi',
        'Officiis velit sunt qui quia ut autem. Est est nihil explicabo voluptatem sit mollitia voluptas. Ex minus sed illum omnis autem quisquam.',
        'product_placeholder.png', '694.33', '2', '580'),
       ('600510', 'omnis',
        'Laboriosam numquam aut beatae porro. Assumenda et quis omnis et doloribus consectetur. Omnis ut repellat doloremque quo nemo. Eum doloremque aspernatur illo id. Dolor est aut corrupti tempore quod rem.',
        'product_placeholder.png', '1837.61', '2', '898'),
       ('607567', 'quia',
        'Facilis voluptas et est atque eum minima sit. Voluptatem quaerat explicabo debitis qui corporis molestiae. Esse hic eaque tempora libero. Unde officiis ipsum at harum ut itaque consectetur.',
        'product_placeholder.png', '1353.83', '2', '258'),
       ('611594', 'tenetur',
        'Dolore veniam saepe ea maiores illum rerum. Sunt non voluptatem laboriosam velit. Culpa nemo rem voluptas voluptas sunt omnis maxime. Vel soluta consequatur asperiores maiores sed ipsum.',
        'product_placeholder.png', '1995.57', '2', '280'),
       ('611876', 'qui',
        'Ut ut quam aut laborum dolore quia. Numquam veniam excepturi consequatur sit et laboriosam dolor. Est enim enim maxime quod nesciunt.',
        'product_placeholder.png', '516.05', '1', '537'),
       ('629082', 'minima',
        'Quia qui alias in voluptate totam. Quis ipsam non harum ad provident est. Et eum repellat voluptates consequuntur. Debitis voluptas laboriosam occaecati eius. Maiores asperiores ut consectetur sit quibusdam corrupti.',
        'product_placeholder.png', '1137.35', '4', '270'),
       ('632452', 'error',
        'Quae vero facere autem et temporibus ut nisi mollitia. Rerum temporibus dolore et est et autem saepe ut. Voluptatem ipsa explicabo est natus ad ut. Laborum sint voluptatem exercitationem ipsam omnis iure.',
        'product_placeholder.png', '619.24', '6', '233'),
       ('639418', 'esse',
        'Doloribus maiores et sed quo. Corrupti magnam aut sunt aliquam perferendis perspiciatis. Et ea quasi eveniet debitis molestiae nihil. Totam dolor et incidunt distinctio qui. Soluta doloremque repellat tempora accusantium iste.',
        'product_placeholder.png', '545.39', '1', '459'),
       ('653367', 'aliquid',
        'Et magni ipsa deserunt nemo. Eos quo voluptatem non quaerat veniam sit animi. Ipsum explicabo dicta aliquid maiores dolorem atque unde quo. Reiciendis adipisci iusto voluptas molestias consequatur facilis.',
        'product_placeholder.png', '921.04', '6', '869'),
       ('658788', 'dolorem',
        'Ut dolores autem in omnis. Maiores rem voluptas architecto cumque sint et inventore. Ab excepturi doloremque modi nulla voluptatum non unde ipsam. Consequatur odit laudantium doloremque voluptas quidem.',
        'product_placeholder.png', '1899.64', '4', '478'),
       ('669117', 'et', 'Ut culpa aut eum id quod corporis numquam. Qui expedita enim occaecati est.', 'product_placeholder.png', '1114.75',
        '3', '958'),
       ('669562', 'accusamus',
        'Vel et facere officiis soluta ipsam laudantium. Voluptas ab vel labore qui quod voluptatem. Id quia veritatis nihil quia molestias et.',
        'product_placeholder.png', '506.5', '5', '835'),
       ('694014', 'sit',
        'Error deleniti adipisci et sunt aspernatur incidunt accusantium. Et amet ut soluta et. Qui officiis excepturi cupiditate vitae. Ad voluptatum ea accusantium maiores ab temporibus sapiente. Magnam quia at at ea et quia atque.',
        'product_placeholder.png', '1233.96', '6', '945'),
       ('703791', 'doloremque',
        'Autem ipsa suscipit repellat est veniam eligendi tempora ut. Ut eum aut et magnam error eos nemo. Impedit quis odit et.',
        'product_placeholder.png', '1071.81', '3', '129'),
       ('720665', 'magni',
        'Impedit aut rerum magnam corrupti temporibus dignissimos. Sit quia eligendi impedit labore exercitationem cum et tempore. Laboriosam qui qui laboriosam eum officia. Ratione optio tempora animi quia harum est quaerat.',
        'product_placeholder.png', '912.46', '5', '413'),
       ('727760', 'aut',
        'Molestiae consequatur eum voluptatem. Nam fuga aut occaecati enim voluptatem accusamus. Recusandae aspernatur saepe architecto quas.',
        'product_placeholder.png', '1056.76', '1', '186'),
       ('727793', 'quidem',
        'Modi sunt temporibus minima doloremque odit quidem recusandae. Optio in molestias qui. Ad recusandae incidunt quia soluta quasi et.',
        'product_placeholder.png', '1752.04', '2', '620'),
       ('735883', 'veniam', 'Aut facilis voluptatem quos placeat. Enim a qui quisquam. Cupiditate et iusto quae repellendus et esse dolor.',
        'product_placeholder.png', '517.49', '4', '492'),
       ('747451', 'voluptate',
        'Quia dolores modi corporis id non possimus. Ut error ut exercitationem repudiandae id sapiente. Est maiores temporibus deserunt itaque ea. Aut dicta voluptate dolorem atque et est.',
        'product_placeholder.png', '1247.8', '3', '196'),
       ('760420', 'ut',
        'Tempore quas at et. Dicta reprehenderit ipsum voluptas nulla eum et. Excepturi aut consectetur ut ducimus. Eligendi velit illo omnis quae minima.',
        'product_placeholder.png', '714.67', '1', '357'),
       ('761415', 'et',
        'Adipisci omnis aut ab deserunt. Quo quasi sed debitis in rerum fugiat. Enim repudiandae dolorum dolorum laboriosam. Aliquam odit quae qui dolorem et consequuntur iure.',
        'product_placeholder.png', '285.64', '4', '286'),
       ('762894', 'sit',
        'Quis quod qui fuga voluptatem ratione et. Qui ipsum sint et officia unde voluptate. Odio eveniet aspernatur est molestias nam amet quod. Sequi tempore eum vero architecto adipisci autem itaque aspernatur.',
        'product_placeholder.png', '1327.87', '5', '372'),
       ('770320', 'cum',
        'Sit similique est tempore maiores. Deserunt est nobis deleniti veniam voluptatem. Aperiam et sed laudantium temporibus at. Officia voluptates voluptas aut.',
        'product_placeholder.png', '1617.9', '6', '508'),
       ('771892', 'rerum',
        'Illum qui aut deserunt illum officiis eos. Modi molestiae quis illo. Eius sed eos rerum id aliquid veniam nemo. Excepturi eligendi eveniet ducimus.',
        'product_placeholder.png', '365.12', '6', '489'),
       ('779249', 'dolor',
        'Laudantium culpa consequuntur iusto dolores voluptatem architecto placeat. Vel tempore sequi aut aut maxime molestiae. Recusandae molestiae esse iusto.',
        'product_placeholder.png', '790.25', '3', '110'),
       ('784864', 'dignissimos',
        'Ea sed est sit aut velit sed. Vitae enim minus illo consequatur qui voluptate aut. In delectus nostrum ab. Soluta et qui maxime dolorum eum modi debitis.',
        'product_placeholder.png', '1814.77', '5', '436'),
       ('785188', 'similique',
        'Nisi amet porro quam voluptates facilis. Ut repellendus quo deserunt consequatur voluptatem. Aperiam magnam esse blanditiis accusantium fuga. Laboriosam qui et vitae eligendi alias.',
        'product_placeholder.png', '1365.2', '2', '130'),
       ('802551', 'hic', 'Sed et modi quis illum laboriosam. Pariatur error quo velit. Cupiditate possimus non culpa hic.',
        'product_placeholder.png', '973.59', '4', '791'),
       ('813724', 'nisi',
        'Nulla ea explicabo molestiae id soluta. Facilis ea est suscipit pariatur consequatur. Facilis dicta id qui dolore.',
        'product_placeholder.png', '1176.76', '4', '319'),
       ('818859', 'non',
        'Explicabo voluptatum quaerat temporibus distinctio ducimus quod minus veritatis. Illo mollitia quos aut architecto molestiae unde vero. Voluptas mollitia sed eum aut quae accusantium. Aut sed dicta et provident.',
        'product_placeholder.png', '685.97', '2', '980'),
       ('827425', 'placeat',
        'Ab iste ipsam maxime deleniti. Iste laudantium ullam voluptatem eius suscipit ea. Enim quis facilis quam corrupti veritatis.',
        'product_placeholder.png', '795.91', '2', '318'),
       ('847667', 'ad', 'Voluptas ducimus aliquid at. Aut officia dolores sint quia. Fuga enim recusandae excepturi.',
        'product_placeholder.png', '1603.29', '2', '781'),
       ('866041', 'magnam',
        'Et rerum temporibus omnis et eius rem vel quia. Maxime dolore ullam id ut libero. Aut voluptatum quae laudantium nobis. Quas nesciunt doloribus nisi ut doloremque qui.',
        'product_placeholder.png', '1073.81', '6', '163'),
       ('873640', 'enim',
        'Libero dignissimos excepturi unde et reiciendis. Minus nemo exercitationem temporibus enim. Deleniti molestiae sit et consequuntur est non eligendi.',
        'product_placeholder.png', '1322.1', '6', '587'),
       ('877060', 'aut', 'Aut cum est qui omnis. A cum quaerat rerum iure et. Quibusdam ad sit qui qui.', 'product_placeholder.png',
        '1968.65', '4', '15'),
       ('884016', 'quia',
        'Fuga ut eveniet ea ad quia. Ut explicabo iste perferendis illo tenetur et aut voluptate. Inventore doloribus soluta voluptatem temporibus facilis in qui placeat.',
        'product_placeholder.png', '478.28', '1', '937'),
       ('889043', 'perspiciatis',
        'Maiores quasi repellat blanditiis hic ex. Et et exercitationem sint impedit id enim modi. Vero et qui occaecati velit delectus repellendus eaque.',
        'product_placeholder.png', '407.93', '4', '150'),
       ('894358', 'suscipit',
        'Mollitia quo nisi quidem et expedita. Quod maiores qui perspiciatis voluptatem. Ex adipisci ullam magni nostrum corrupti. Ipsa quia cumque sunt maxime dolor qui quia inventore.',
        'product_placeholder.png', '305.05', '4', '927'),
       ('898250', 'quas',
        'Velit asperiores repellat reiciendis qui corporis consectetur aliquid. Quas qui provident quibusdam vel recusandae. Ea temporibus labore omnis commodi voluptas excepturi.',
        'product_placeholder.png', '394.93', '3', '761'),
       ('903141', 'officiis',
        'Placeat eos sequi amet omnis corporis vel perferendis. Aliquam reiciendis eveniet similique animi ut qui similique. Sit nostrum voluptatem excepturi et ipsam. Et voluptates qui soluta quae rem nihil autem.',
        'product_placeholder.png', '1053.11', '1', '744'),
       ('920800', 'esse',
        'Veniam est veniam ut et quod. Atque incidunt voluptatem porro vel. Quis nulla saepe asperiores voluptatem omnis dolores omnis. Itaque qui expedita adipisci in consequatur.',
        'product_placeholder.png', '1312.63', '6', '746'),
       ('927733', 'architecto',
        'Est amet sunt quia cum rerum blanditiis sed. Hic et temporibus est impedit. Exercitationem quam enim ipsum quos. Ab aut aliquid temporibus beatae quaerat nihil in.',
        'product_placeholder.png', '1868.91', '5', '844'),
       ('929004', 'iste', 'Illum perferendis in porro enim nihil sed. Est qui alias impedit. Similique harum vero sint id et assumenda.',
        'product_placeholder.png', '1283.93', '3', '855'),
       ('953627', 'dolorem', 'Eum atque vitae molestiae blanditiis impedit qui. Aliquam quod similique non nemo omnis repellat quia.',
        'product_placeholder.png', '1141.41', '5', '648'),
       ('962207', 'consequuntur',
        'Error et sed dolores sit sed voluptatem dolores. Ea qui commodi sed iusto. Inventore odio et omnis totam explicabo.',
        'product_placeholder.png', '1879.8', '6', '126'),
       ('968643', 'beatae',
        'Quo ut omnis ut laboriosam quis quasi voluptatibus. Ipsam minima quas ab eligendi facilis. Perspiciatis dolor possimus reiciendis excepturi incidunt repudiandae at. Sunt ipsam occaecati a consequatur eos. Blanditiis laudantium non omnis incidunt vitae acc',
        'product_placeholder.png', '301.25', '3', '681'),
       ('981065', 'maxime',
        'Earum ad sit quam magni sunt quas corrupti. Quis assumenda dolor quaerat corrupti excepturi nobis. Sit ut quo labore sint deleniti et. Quaerat fuga architecto consequatur ex mollitia accusamus.',
        'product_placeholder.png', '1651.59', '1', '75'),
       ('996768', 'eaque',
        'Voluptas quibusdam animi quia velit id ratione impedit. Aut fugiat corrupti rerum ratione fugiat. Autem asperiores optio rerum quia alias voluptas. Accusantium officia voluptatibus sint iusto aut eos.',
        'product_placeholder.png', '687.57', '1', '745');